Part 1 from the main terminal after making a prediction (Reference: https://knowledge.udacity.com/questions/79267 )
Error from server (AlreadyExists): pods "mlapp" already exists
NAME    READY   STATUS    RESTARTS   AGE
mlapp   1/1     Running   0          43s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

Part 2 from secondary terminal, displaying the logs for kubectl logs mlapp (Reference: https://knowledge.udacity.com/questions/79267 )
[2021-10-20 21:14:32,508] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-10-20 21:14:32,520] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-10-20 21:14:32,528] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-10-20 21:14:32,531] INFO in app: output prediction: [20.35373177134412]
127.0.0.1 - - [20/Oct/2021 21:14:32] "POST /predict HTTP/1.1" 200 -